[package]
name = "tavra-c"
version = "0.1.0"
edition = "2024"
description = "C API for Tavra"
license = "Apache-2.0"
repository = "https://github.com/SkuldNorniern/tavra"

[lib]
crate-type = ["cdylib", "staticlib", "rlib"]

[dependencies]
tavra = { path = "..", version = "0.1.0" }

[lints]
workspace = true
