[package]
name = "tavra-fuzz"
version = "0.0.0"
publish = false
edition = "2024"

[package.metadata]
cargo-fuzz = true

[dependencies]
libfuzzer-sys = "0.4"
tavra = { path = "..", default-features = false, features = ["binary", "envelope"] }

[[bin]]
name = "text"
path = "fuzz_targets/text.rs"
test = false
doc = false
bench = false

[[bin]]
name = "binary"
path = "fuzz_targets/binary.rs"
test = false
doc = false
bench = false

[[bin]]
name = "envelope"
path = "fuzz_targets/envelope.rs"
test = false
doc = false
bench = false

[[bin]]
name = "schema"
path = "fuzz_targets/schema.rs"
test = false
doc = false
bench = false
